#!/usr/bin/env tclsh

proc read_lines {path} {
  set channel [open $path r]
  set data [read $channel]
  close $channel
  return [split $data "\n"]
}

proc split_dat_line {line} {
  set cols {}
  foreach value [split $line "\t"] {
    lappend cols [string trim $value]
  }
  return $cols
}

proc find_mib_file {mib_dir filename} {
  set lower [string tolower $filename]
  set upper [string toupper $filename]
  foreach candidate [list $filename $lower $upper] {
    set path [file join $mib_dir $candidate]
    if {[file exists $path]} {
      return $path
    }
  }
  error "Unable to locate $filename in $mib_dir"
}

proc sanitize_identifier {raw fallback} {
  set name [string trim $raw]
  if {$name eq ""} {
    set name $fallback
  }

  regsub -all {[^A-Za-z0-9_]} $name {_} name
  regsub -all {_+} $name {_} name
  set name [string trim $name _]

  if {[regexp {^TC[0-9]} $name]} {
    regsub {^TC} $name {TC_} name
  }

  if {$name eq ""} {
    set name $fallback
  }

  if {[regexp {^[0-9]} $name]} {
    set name "tc_$name"
  }

  return $name
}

proc is_required_param {param_name kind} {
  if {[string tolower [string trim $param_name]] eq "filler"} {
    return 0
  }

  if {[string toupper [string trim $kind]] eq "A"} {
    return 0
  }

  return 1
}

proc is_variable_length_param {bit_length} {
  return [expr {[string trim $bit_length] eq "0"}]
}

proc build_command_index {mib_dir} {
  set ccf_path [find_mib_file $mib_dir "ccf.dat"]
  set cdf_path [find_mib_file $mib_dir "cdf.dat"]

  set commands [dict create]

  foreach line [read_lines $ccf_path] {
    set trimmed [string trim $line]
    if {$trimmed eq "" || [string first "#" $trimmed] == 0} {
      continue
    }

    set cols [split_dat_line $line]
    set tc_id [lindex $cols 0]
    if {$tc_id eq ""} {
      continue
    }

    set friendly [lindex $cols 1]
    set description [lindex $cols 2]

    dict set commands $tc_id [dict create \
      id $tc_id \
      friendly $friendly \
      description $description \
      params {}]
  }

  foreach line [read_lines $cdf_path] {
    set trimmed [string trim $line]
    if {$trimmed eq "" || [string first "#" $trimmed] == 0} {
      continue
    }

    set cols [split_dat_line $line]
    set tc_id [lindex $cols 0]
    if {$tc_id eq "" || ![dict exists $commands $tc_id]} {
      continue
    }

    set param [dict create \
      kind [lindex $cols 1] \
      name [lindex $cols 2] \
      bit_length [lindex $cols 3] \
      param_id [lindex $cols 6]]

    set entry [dict get $commands $tc_id]
    set params [dict get $entry params]
    lappend params $param
    dict set entry params $params
    dict set commands $tc_id $entry
  }

  return $commands
}

proc render_mock_file {commands out_file} {
  set channel [open $out_file w]

  puts $channel "# Auto-generated mock telecommand procedures."
  puts $channel "# Generated by examples/generate_mock_commands.tcl"
  puts $channel ""

  set used_proc_names [dict create]

  foreach tc_id [lsort [dict keys $commands]] {
    set entry [dict get $commands $tc_id]
    set friendly [dict get $entry friendly]

    if {[string trim $friendly] eq ""} {
      set proc_base [sanitize_identifier $tc_id $tc_id]
    } else {
      set proc_base [sanitize_identifier $friendly $tc_id]
    }

    set proc_name $proc_base
    if {[dict exists $used_proc_names $proc_name]} {
      set proc_name "${proc_base}_[sanitize_identifier $tc_id $tc_id]"
    }
    set suffix 2
    while {[dict exists $used_proc_names $proc_name]} {
      set proc_name "${proc_base}_$suffix"
      incr suffix
    }
    dict set used_proc_names $proc_name 1

    set required_params {}
    set optional_params {}
    set variable_params {}
    set index 1

    foreach param [dict get $entry params] {
      set raw_param_name [dict get $param param_id]
      if {[string trim $raw_param_name] eq ""} {
        set raw_param_name [dict get $param name]
      }
      if {[string trim $raw_param_name] eq ""} {
        set raw_param_name "param$index"
      }

      set arg_name [sanitize_identifier $raw_param_name "param$index"]
      set kind [dict get $param kind]
      set display_name [dict get $param name]
      set bit_length [dict get $param bit_length]

      set param_spec [dict create \
        raw $raw_param_name \
        arg $arg_name \
        display $display_name \
        kind $kind \
        bit_length $bit_length]

      if {[is_variable_length_param $bit_length]} {
        lappend variable_params $param_spec
      } elseif {[is_required_param $display_name $kind]} {
        lappend required_params $param_spec
      } else {
        lappend optional_params $param_spec
      }

      incr index
    }

    set arg_spec {}
    foreach param_spec $required_params {
      lappend arg_spec [dict get $param_spec arg]
    }
    foreach param_spec $optional_params {
      lappend arg_spec [list [dict get $param_spec arg] ""]
    }
    if {[llength $variable_params] > 0} {
      lappend arg_spec args
    }

    set arg_spec_text [list {*}$arg_spec]
    puts $channel "proc $proc_name {$arg_spec_text} {"
    puts $channel "    # $tc_id: [dict get $entry description]"
    puts $channel [format {    set payload [list %s]} $tc_id]

    foreach param_spec $required_params {
      set raw [dict get $param_spec raw]
      set arg [dict get $param_spec arg]
      puts $channel [format {    lappend payload [list {%s} $%s]} $raw $arg]
    }

    foreach param_spec $optional_params {
      set raw [dict get $param_spec raw]
      set arg [dict get $param_spec arg]
      puts $channel [format {    if {$%s ne ""} { lappend payload [list {%s} $%s] }} $arg $raw $arg]
    }

    if {[llength $variable_params] > 0} {
      set variable_names {}
      foreach param_spec $variable_params {
        lappend variable_names [dict get $param_spec raw]
      }

      puts $channel "    # Variable-length parameter(s): [join $variable_names ", "]"
      foreach variable_name $variable_names {
        puts $channel [format {    if {[llength $args] > 0} { lappend payload [list {%s} $args] }} $variable_name]
      }
    }

    puts $channel "    return \$payload"
    puts $channel "}"
    puts $channel ""
  }

  close $channel
}

set script_dir [file dirname [file normalize [info script]]]
set mib_dir [file join $script_dir .. mibs ASCII_CSIM]
if {[llength $argv] >= 1} {
  set mib_dir [lindex $argv 0]
}
set mib_dir [file normalize $mib_dir]

set out_file [file join $script_dir mock_commands.tcl]
if {[llength $argv] >= 2} {
  set out_file [lindex $argv 1]
}
set out_file [file normalize $out_file]

set commands [build_command_index $mib_dir]
render_mock_file $commands $out_file

puts "Generated [llength [dict keys $commands]] mock procs in $out_file"
