# Auto-generated mock telecommand procedures.
# Generated by examples/generate_mock_commands.tcl

proc TC_2_1 {S2KCP001 S2KCP002 S2KCP003} {
    # S2KTC001: Distribute On-Off Commands
    set payload [list S2KTC001]
    lappend payload [list {S2KCP001} $S2KCP001]
    lappend payload [list {S2KCP002} $S2KCP002]
    lappend payload [list {S2KCP003} $S2KCP003]
    return $payload
}

proc TC_2_2 {S2KCP004 S2KCP005 S2KCP006 S2KCP007} {
    # S2KTC002: Distribute Register Load Commands
    set payload [list S2KTC002]
    lappend payload [list {S2KCP004} $S2KCP004]
    lappend payload [list {S2KCP005} $S2KCP005]
    lappend payload [list {S2KCP006} $S2KCP006]
    lappend payload [list {S2KCP007} $S2KCP007]
    return $payload
}

proc TC_2_3 {S2KCP008 S2KCP009} {
    # S2KTC003: Distribute CPDU Commands
    set payload [list S2KTC003]
    lappend payload [list {S2KCP008} $S2KCP008]
    lappend payload [list {S2KCP009} $S2KCP009]
    return $payload
}

proc TC_2_3_S2KTC004 {S2KCP008 S2KCP009} {
    # S2KTC004: Distribute CPDU Commands
    set payload [list S2KTC004]
    lappend payload [list {S2KCP008} $S2KCP008]
    lappend payload [list {S2KCP009} $S2KCP009]
    return $payload
}

proc TC_3_1 {S2KCP013 S2KCP015 S2KCP016} {
    # S2KTC005: Define New Housekeeping Parameter Report
    set payload [list S2KTC005]
    lappend payload [list {S2KCP013} $S2KCP013]
    lappend payload [list {S2KCP015} $S2KCP015]
    lappend payload [list {S2KCP016} $S2KCP016]
    return $payload
}

proc TC_3_2 {S2KCP014 S2KCP017 S2KCP018 S2KCP019} {
    # S2KTC006: Define New Diagnostic Parameter Report
    set payload [list S2KTC006]
    lappend payload [list {S2KCP014} $S2KCP014]
    lappend payload [list {S2KCP017} $S2KCP017]
    lappend payload [list {S2KCP018} $S2KCP018]
    lappend payload [list {S2KCP019} $S2KCP019]
    return $payload
}

proc TC_3_3 {S2KCP013} {
    # S2KTC007: Clear Housekeeping Parameter Report Definitions
    set payload [list S2KTC007]
    lappend payload [list {S2KCP013} $S2KCP013]
    return $payload
}

proc TC_3_4 {S2KCP014} {
    # S2KTC008: Clear Diagnostic Parameter Report Definitions
    set payload [list S2KTC008]
    lappend payload [list {S2KCP014} $S2KCP014]
    return $payload
}

proc TC_3_5 {S2KCP013} {
    # S2KTC009: Enable Housekeeping Parameter Report Generation
    set payload [list S2KTC009]
    lappend payload [list {S2KCP013} $S2KCP013]
    return $payload
}

proc TC_3_6 {S2KCP013} {
    # S2KTC010: Disable Housekeeping Parameter Report Generation
    set payload [list S2KTC010]
    lappend payload [list {S2KCP013} $S2KCP013]
    return $payload
}

proc TC_3_7 {S2KCP014} {
    # S2KTC011: Enable Diagnostic Parameter Report Generation
    set payload [list S2KTC011]
    lappend payload [list {S2KCP014} $S2KCP014]
    return $payload
}

proc TC_3_8 {S2KCP014} {
    # S2KTC012: Disable Diagnostic Parameter Report Generation
    set payload [list S2KTC012]
    lappend payload [list {S2KCP014} $S2KCP014]
    return $payload
}

proc TC_3_9 {S2KCP013} {
    # S2KTC013: Report Housekeeping Parameter Report Definitions
    set payload [list S2KTC013]
    lappend payload [list {S2KCP013} $S2KCP013]
    return $payload
}

proc TC_3_11 {S2KCP014} {
    # S2KTC014: Report Diagnostic Parameter Report Definitions
    set payload [list S2KTC014]
    lappend payload [list {S2KCP014} $S2KCP014]
    return $payload
}

proc TC_3_13 {S2KCP013} {
    # S2KTC015: Report Housekeeping Parameter Sampling Time Offsets
    set payload [list S2KTC015]
    lappend payload [list {S2KCP013} $S2KCP013]
    return $payload
}

proc TC_3_14 {S2KCP014} {
    # S2KTC016: Report Diagnostic Parameter Sampling Time Offsets
    set payload [list S2KTC016]
    lappend payload [list {S2KCP014} $S2KCP014]
    return $payload
}

proc TC_3_17 {S2KCP013} {
    # S2KTC017: Select Periodic Housekeeping Parameter Report Generation Mode
    set payload [list S2KTC017]
    lappend payload [list {S2KCP013} $S2KCP013]
    return $payload
}

proc TC_3_18 {S2KCP014} {
    # S2KTC018: Select Periodic Diagnostic Parameter Report Generation Mode
    set payload [list S2KTC018]
    lappend payload [list {S2KCP014} $S2KCP014]
    return $payload
}

proc TC_3_19 {S2KCP013 S2KCP015 S2KCP016} {
    # S2KTC019: Select Filtered Housekeeping Parameter Report Generation Mode
    set payload [list S2KTC019]
    lappend payload [list {S2KCP013} $S2KCP013]
    lappend payload [list {S2KCP015} $S2KCP015]
    lappend payload [list {S2KCP016} $S2KCP016]
    return $payload
}

proc TC_3_20 {S2KCP014 S2KCP018 S2KCP019} {
    # S2KTC020: Select Filtered Diagnostic Parameter Report Generation Mode
    set payload [list S2KTC020]
    lappend payload [list {S2KCP014} $S2KCP014]
    lappend payload [list {S2KCP018} $S2KCP018]
    lappend payload [list {S2KCP019} $S2KCP019]
    return $payload
}

proc TC_3_21 {S2KCP013} {
    # S2KTC021: Report Unfiltered Housekeeping Parameters
    set payload [list S2KTC021]
    lappend payload [list {S2KCP013} $S2KCP013]
    return $payload
}

proc TC_3_22 {S2KCP014} {
    # S2KTC022: Report Unfiltered Diagnostic Parameters
    set payload [list S2KTC022]
    lappend payload [list {S2KCP014} $S2KCP014]
    return $payload
}

proc TC_4_1 {S2KCP024} {
    # S2KTC023: Report Parameter Statistics
    set payload [list S2KTC023]
    lappend payload [list {S2KCP024} $S2KCP024]
    return $payload
}

proc TC_4_3 {} {
    # S2KTC024: Reset Parameter Statistics Reporting
    set payload [list S2KTC024]
    return $payload
}

proc TC_4_4 {} {
    # S2KTC025: Enable Periodic Parameter Statistics Reporting
    set payload [list S2KTC025]
    return $payload
}

proc TC_4_5 {} {
    # S2KTC026: Disable Periodic Parameter Statistics Reporting
    set payload [list S2KTC026]
    return $payload
}

proc TC_4_6 {S2KCP025} {
    # S2KTC027: Add Parameters To Parameter Statistics List
    set payload [list S2KTC027]
    lappend payload [list {S2KCP025} $S2KCP025]
    return $payload
}

proc TC_4_7 {S2KCP025} {
    # S2KTC028: Delete Parameters To Parameter Statistics List
    set payload [list S2KTC028]
    lappend payload [list {S2KCP025} $S2KCP025]
    return $payload
}

proc TC_4_8 {} {
    # S2KTC029: Report Parameter Statistics List
    set payload [list S2KTC029]
    return $payload
}

proc TC_4_10 {} {
    # S2KTC030: Clear Parameter Statistics List
    set payload [list S2KTC030]
    return $payload
}

proc TC_5_5 {S2KCP026} {
    # S2KTC031: Enable Event Report Generation
    set payload [list S2KTC031]
    lappend payload [list {S2KCP026} $S2KCP026]
    return $payload
}

proc TC_5_6 {S2KCP026} {
    # S2KTC032: Disable Event Report Generation
    set payload [list S2KTC032]
    lappend payload [list {S2KCP026} $S2KCP026]
    return $payload
}

proc TC_6_1 {S2KCP027 S2KCP029 S2KCP030 S2KCP031 {Filler {}} args} {
    # S2KTC033: Load Memory Using Base Address Plus Offsets
    set payload [list S2KTC033]
    lappend payload [list {S2KCP027} $S2KCP027]
    lappend payload [list {S2KCP029} $S2KCP029]
    lappend payload [list {S2KCP030} $S2KCP030]
    lappend payload [list {S2KCP031} $S2KCP031]
    if {$Filler ne ""} { lappend payload [list {Filler} $Filler] }
    # Variable-length parameter(s): S2KCP032
    if {[llength $args] > 0} { lappend payload [list {S2KCP032} $args] }
    return $payload
}

proc TC_6_2 {S2KCP027 S2KCP033 S2KCP031 {Filler {}} args} {
    # S2KTC034: Load Memory Using Absolute Addresses
    set payload [list S2KTC034]
    lappend payload [list {S2KCP027} $S2KCP027]
    lappend payload [list {S2KCP033} $S2KCP033]
    lappend payload [list {S2KCP031} $S2KCP031]
    if {$Filler ne ""} { lappend payload [list {Filler} $Filler] }
    # Variable-length parameter(s): S2KCP032
    if {[llength $args] > 0} { lappend payload [list {S2KCP032} $args] }
    return $payload
}

proc TC_6_3 {S2KCP027 S2KCP029 S2KCP030 S2KCP031 {Filler {}}} {
    # S2KTC035: Dump Memory Using Base Address Plus Offsets
    set payload [list S2KTC035]
    lappend payload [list {S2KCP027} $S2KCP027]
    lappend payload [list {S2KCP029} $S2KCP029]
    lappend payload [list {S2KCP030} $S2KCP030]
    lappend payload [list {S2KCP031} $S2KCP031]
    if {$Filler ne ""} { lappend payload [list {Filler} $Filler] }
    return $payload
}

proc TC_6_5 {S2KCP027 S2KCP033 S2KCP031 {Memory_ID {}}} {
    # S2KTC036: Dump Memory Using Absolute Addresses
    set payload [list S2KTC036]
    lappend payload [list {S2KCP027} $S2KCP027]
    lappend payload [list {S2KCP033} $S2KCP033]
    lappend payload [list {S2KCP031} $S2KCP031]
    if {$Memory_ID ne ""} { lappend payload [list {Memory ID} $Memory_ID] }
    return $payload
}

proc TC_6_7 {S2KCP027 S2KCP029 S2KCP030 S2KCP031 {Filler {}}} {
    # S2KTC037: Check Memory Using Base Address Plus Offsets
    set payload [list S2KTC037]
    lappend payload [list {S2KCP027} $S2KCP027]
    lappend payload [list {S2KCP029} $S2KCP029]
    lappend payload [list {S2KCP030} $S2KCP030]
    lappend payload [list {S2KCP031} $S2KCP031]
    if {$Filler ne ""} { lappend payload [list {Filler} $Filler] }
    return $payload
}

proc TC_6_9 {S2KCP027 S2KCP033 S2KCP031 {Filler {}}} {
    # S2KTC038: Check Memory Using Absolute Addresses
    set payload [list S2KTC038]
    lappend payload [list {S2KCP027} $S2KCP027]
    lappend payload [list {S2KCP033} $S2KCP033]
    lappend payload [list {S2KCP031} $S2KCP031]
    if {$Filler ne ""} { lappend payload [list {Filler} $Filler] }
    return $payload
}

proc TC_8_1 {S2KCP034 S2KCP089 S2KCP090} {
    # S2KTC039: Perform Function
    set payload [list S2KTC039]
    lappend payload [list {S2KCP034} $S2KCP034]
    lappend payload [list {S2KCP089} $S2KCP089]
    lappend payload [list {S2KCP090} $S2KCP090]
    return $payload
}

proc TC_9_1 {S2KCP035} {
    # S2KTC040: Change Time Report Generation Rate
    set payload [list S2KTC040]
    lappend payload [list {S2KCP035} $S2KCP035]
    return $payload
}

proc TC_11_1 {S2KCP036} {
    # S2KTC041: Enable Release Of Telecommands
    set payload [list S2KTC041]
    lappend payload [list {S2KCP036} $S2KCP036]
    return $payload
}

proc TC_11_2 {S2KCP036} {
    # S2KTC042: Disable Release Of Telecommands
    set payload [list S2KTC042]
    lappend payload [list {S2KCP036} $S2KCP036]
    return $payload
}

proc TC_11_3 {} {
    # S2KTC043: Reset Command Schedule
    set payload [list S2KTC043]
    return $payload
}

proc TC_11_4 {S2KCP037 S2KCP038 args} {
    # S2KTC044: Insert Telecommands In Command Schedule
    set payload [list S2KTC044]
    lappend payload [list {S2KCP037} $S2KCP037]
    lappend payload [list {S2KCP038} $S2KCP038]
    # Variable-length parameter(s): S2KCP039
    if {[llength $args] > 0} { lappend payload [list {S2KCP039} $args] }
    return $payload
}

proc TC_11_5 {S2KCP040 S2KCP042 S2KCP047 {Filler {}}} {
    # S2KTC045: Delete Telecommands
    set payload [list S2KTC045]
    lappend payload [list {S2KCP040} $S2KCP040]
    lappend payload [list {S2KCP042} $S2KCP042]
    lappend payload [list {S2KCP047} $S2KCP047]
    if {$Filler ne ""} { lappend payload [list {Filler} $Filler] }
    return $payload
}

proc TC_11_6 {S2KCP043 S2KCP044 S2KCP045 S2KCP037 S2KCP040} {
    # S2KTC046: Delete Telecommands Over Time Period
    set payload [list S2KTC046]
    lappend payload [list {S2KCP043} $S2KCP043]
    lappend payload [list {S2KCP044} $S2KCP044]
    lappend payload [list {S2KCP045} $S2KCP045]
    lappend payload [list {S2KCP037} $S2KCP037]
    lappend payload [list {S2KCP040} $S2KCP040]
    return $payload
}

proc TC_11_7 {S2KCP046 S2KCP040 S2KCP042 S2KCP047 S2KCP312 S2KCP315 S2KCP316 S2KCP317 {Filler {}}} {
    # S2KTC047: Time-Shift Selected Telecommands
    set payload [list S2KTC047]
    lappend payload [list {S2KCP046} $S2KCP046]
    lappend payload [list {S2KCP040} $S2KCP040]
    lappend payload [list {S2KCP042} $S2KCP042]
    lappend payload [list {S2KCP047} $S2KCP047]
    lappend payload [list {S2KCP312} $S2KCP312]
    lappend payload [list {S2KCP315} $S2KCP315]
    lappend payload [list {S2KCP316} $S2KCP316]
    lappend payload [list {S2KCP317} $S2KCP317]
    if {$Filler ne ""} { lappend payload [list {Filler} $Filler] }
    return $payload
}

proc TC_11_8 {S2KCP043 S2KCP044 S2KCP045 S2KCP046 S2KCP037 S2KCP040 S2KCP318 S2KCP319} {
    # S2KTC048: Time-Shift Selected Telecommands Over Time Period
    set payload [list S2KTC048]
    lappend payload [list {S2KCP043} $S2KCP043]
    lappend payload [list {S2KCP044} $S2KCP044]
    lappend payload [list {S2KCP045} $S2KCP045]
    lappend payload [list {S2KCP046} $S2KCP046]
    lappend payload [list {S2KCP037} $S2KCP037]
    lappend payload [list {S2KCP040} $S2KCP040]
    lappend payload [list {S2KCP318} $S2KCP318]
    lappend payload [list {S2KCP319} $S2KCP319]
    return $payload
}

proc TC_11_9 {S2KCP040 S2KCP042 S2KCP047 {Filler {}}} {
    # S2KTC049: Report Subset Of Command Schedule In Detailed Form
    set payload [list S2KTC049]
    lappend payload [list {S2KCP040} $S2KCP040]
    lappend payload [list {S2KCP042} $S2KCP042]
    lappend payload [list {S2KCP047} $S2KCP047]
    if {$Filler ne ""} { lappend payload [list {Filler} $Filler] }
    return $payload
}

proc TC_11_11 {S2KCP043 S2KCP044 S2KCP045 S2KCP037 S2KCP040} {
    # S2KTC050: Report Subset Of Schedule In Detailed Form Over Time Period
    set payload [list S2KTC050]
    lappend payload [list {S2KCP043} $S2KCP043]
    lappend payload [list {S2KCP044} $S2KCP044]
    lappend payload [list {S2KCP045} $S2KCP045]
    lappend payload [list {S2KCP037} $S2KCP037]
    lappend payload [list {S2KCP040} $S2KCP040]
    return $payload
}

proc TC_11_12 {} {
    # S2KTC051: Report Subset Of Command Schedule In Summary Form
    set payload [list S2KTC051]
    return $payload
}

proc TC_11_14 {S2KCP043 S2KCP044 S2KCP045 S2KCP037 S2KCP040} {
    # S2KTC052: Report Subset Of Schedule In Summary Form Over Time Period
    set payload [list S2KTC052]
    lappend payload [list {S2KCP043} $S2KCP043]
    lappend payload [list {S2KCP044} $S2KCP044]
    lappend payload [list {S2KCP045} $S2KCP045]
    lappend payload [list {S2KCP037} $S2KCP037]
    lappend payload [list {S2KCP040} $S2KCP040]
    return $payload
}

proc TC_11_15 {S2KCP046 S2KCP321 S2KCP322 S2KCP323 S2KCP324 S2KCP325 S2KCP326 S2KCP327 S2KCP328} {
    # S2KTC053: Time Shift All Telecommands
    set payload [list S2KTC053]
    lappend payload [list {S2KCP046} $S2KCP046]
    lappend payload [list {S2KCP321} $S2KCP321]
    lappend payload [list {S2KCP322} $S2KCP322]
    lappend payload [list {S2KCP323} $S2KCP323]
    lappend payload [list {S2KCP324} $S2KCP324]
    lappend payload [list {S2KCP325} $S2KCP325]
    lappend payload [list {S2KCP326} $S2KCP326]
    lappend payload [list {S2KCP327} $S2KCP327]
    lappend payload [list {S2KCP328} $S2KCP328]
    return $payload
}

proc TC_11_16 {} {
    # S2KTC054: Report Command Schedule In Detailed Form
    set payload [list S2KTC054]
    return $payload
}

proc TC_11_17 {} {
    # S2KTC055: Report Command Schedule In Summary Form
    set payload [list S2KTC055]
    return $payload
}

proc TC_11_18 {} {
    # S2KTC056: Report Status Of Command Schedule
    set payload [list S2KTC056]
    return $payload
}

proc TC_12_1 {S2KCP048 S2KCP049} {
    # S2KTC057: Enable Monitoring Of Parameters
    set payload [list S2KTC057]
    lappend payload [list {S2KCP048} $S2KCP048]
    lappend payload [list {S2KCP049} $S2KCP049]
    return $payload
}

proc TC_12_2 {S2KCP048 S2KCP049} {
    # S2KTC058: Disable Monitoring Of Parameters
    set payload [list S2KTC058]
    lappend payload [list {S2KCP048} $S2KCP048]
    lappend payload [list {S2KCP049} $S2KCP049]
    return $payload
}

proc TC_12_3 {} {
    # S2KTC059: Change Maximum Reporting Delay
    set payload [list S2KTC059]
    return $payload
}

proc TC_12_4 {} {
    # S2KTC060: Clear Monitoring List
    set payload [list S2KTC060]
    return $payload
}

proc TC_12_5 {S2KCP050 S2KCP051 S2KCP052 S2KCP053 S2KCP054 S2KCP055} {
    # S2KTC061: Add Parameters To Monitoring List
    set payload [list S2KTC061]
    lappend payload [list {S2KCP050} $S2KCP050]
    lappend payload [list {S2KCP051} $S2KCP051]
    lappend payload [list {S2KCP052} $S2KCP052]
    lappend payload [list {S2KCP053} $S2KCP053]
    lappend payload [list {S2KCP054} $S2KCP054]
    lappend payload [list {S2KCP055} $S2KCP055]
    return $payload
}

proc TC_12_6 {S2KCP049} {
    # S2KTC062: Delete Parameters From Monitoring List
    set payload [list S2KTC062]
    lappend payload [list {S2KCP049} $S2KCP049]
    return $payload
}

proc TC_12_7 {S2KCP050 S2KCP051 S2KCP052 S2KCP053 S2KCP054 S2KCP055} {
    # S2KTC063: Modify Parameter Checking Information
    set payload [list S2KTC063]
    lappend payload [list {S2KCP050} $S2KCP050]
    lappend payload [list {S2KCP051} $S2KCP051]
    lappend payload [list {S2KCP052} $S2KCP052]
    lappend payload [list {S2KCP053} $S2KCP053]
    lappend payload [list {S2KCP054} $S2KCP054]
    lappend payload [list {S2KCP055} $S2KCP055]
    return $payload
}

proc TC_12_8 {} {
    # S2KTC064: Report Current Monitoring List
    set payload [list S2KTC064]
    return $payload
}

proc TC_12_10 {} {
    # S2KTC065: Report Current Parameter Out-Of-Limit List
    set payload [list S2KTC065]
    return $payload
}

proc TC_13_5 {S2KCP056} {
    # S2KTC066: Downlink Reception Acknowledgement
    set payload [list S2KTC066]
    lappend payload [list {S2KCP056} $S2KCP056]
    return $payload
}

proc TC_13_6 {S2KCP057 S2KCP056} {
    # S2KTC067: Repeat Parts
    set payload [list S2KTC067]
    lappend payload [list {S2KCP057} $S2KCP057]
    lappend payload [list {S2KCP056} $S2KCP056]
    return $payload
}

proc TC_13_8 {} {
    # S2KTC068: Abort Downlink
    set payload [list S2KTC068]
    return $payload
}

proc TC_13_9 {S2KCP056 args} {
    # S2KTC069: Accept First Uplink Part
    set payload [list S2KTC069]
    lappend payload [list {S2KCP056} $S2KCP056]
    # Variable-length parameter(s): S2KCP058
    if {[llength $args] > 0} { lappend payload [list {S2KCP058} $args] }
    return $payload
}

proc TC_13_10 {S2KCP056 args} {
    # S2KTC070: Accept Intermediate Uplink Part
    set payload [list S2KTC070]
    lappend payload [list {S2KCP056} $S2KCP056]
    # Variable-length parameter(s): S2KCP058
    if {[llength $args] > 0} { lappend payload [list {S2KCP058} $args] }
    return $payload
}

proc TC_13_11 {S2KCP056 args} {
    # S2KTC071: Accept Last Uplink Part
    set payload [list S2KTC071]
    lappend payload [list {S2KCP056} $S2KCP056]
    # Variable-length parameter(s): S2KCP058
    if {[llength $args] > 0} { lappend payload [list {S2KCP058} $args] }
    return $payload
}

proc TC_13_12 {S2KCP056 args} {
    # S2KTC072: Accept Repeated Part
    set payload [list S2KTC072]
    lappend payload [list {S2KCP056} $S2KCP056]
    # Variable-length parameter(s): S2KCP058
    if {[llength $args] > 0} { lappend payload [list {S2KCP058} $args] }
    return $payload
}

proc TC_13_13 {} {
    # S2KTC073: Abort Reception Of Uplinked Data
    set payload [list S2KTC073]
    return $payload
}

proc TC_14_1 {S2KCP059 S2KCP060 S2KCP061 S2KCP062 S2KCP063 S2KCP064} {
    # S2KTC074: Enable Forwarding Of Telemetry Source Packets
    set payload [list S2KTC074]
    lappend payload [list {S2KCP059} $S2KCP059]
    lappend payload [list {S2KCP060} $S2KCP060]
    lappend payload [list {S2KCP061} $S2KCP061]
    lappend payload [list {S2KCP062} $S2KCP062]
    lappend payload [list {S2KCP063} $S2KCP063]
    lappend payload [list {S2KCP064} $S2KCP064]
    return $payload
}

proc TC_14_2 {S2KCP059 S2KCP060 S2KCP061 S2KCP062 S2KCP063 S2KCP064} {
    # S2KTC075: Disable Forwarding Of Telemetry Source Packets
    set payload [list S2KTC075]
    lappend payload [list {S2KCP059} $S2KCP059]
    lappend payload [list {S2KCP060} $S2KCP060]
    lappend payload [list {S2KCP061} $S2KCP061]
    lappend payload [list {S2KCP062} $S2KCP062]
    lappend payload [list {S2KCP063} $S2KCP063]
    lappend payload [list {S2KCP064} $S2KCP064]
    return $payload
}

proc TC_14_3 {} {
    # S2KTC076: Report Enabled Telemetry Source Packets
    set payload [list S2KTC076]
    return $payload
}

proc TC_14_5 {S2KCP065 S2KCP066 S2KCP067} {
    # S2KTC077: Enable Forwarding Of Housekeeping Packets
    set payload [list S2KTC077]
    lappend payload [list {S2KCP065} $S2KCP065]
    lappend payload [list {S2KCP066} $S2KCP066]
    lappend payload [list {S2KCP067} $S2KCP067]
    return $payload
}

proc TC_14_6 {S2KCP065 S2KCP066 S2KCP067} {
    # S2KTC078: Disable Forwarding Of Housekeeping Packets
    set payload [list S2KTC078]
    lappend payload [list {S2KCP065} $S2KCP065]
    lappend payload [list {S2KCP066} $S2KCP066]
    lappend payload [list {S2KCP067} $S2KCP067]
    return $payload
}

proc TC_14_7 {} {
    # S2KTC079: Report Enabled Housekeeping Packets
    set payload [list S2KTC079]
    return $payload
}

proc TC_14_9 {S2KCP065 S2KCP066 S2KCP067} {
    # S2KTC080: Enable Forwarding Of Diagnostic Packets
    set payload [list S2KTC080]
    lappend payload [list {S2KCP065} $S2KCP065]
    lappend payload [list {S2KCP066} $S2KCP066]
    lappend payload [list {S2KCP067} $S2KCP067]
    return $payload
}

proc TC_14_10 {S2KCP065 S2KCP066 S2KCP067} {
    # S2KTC081: Disable Forwarding Of Diagnostic Packets
    set payload [list S2KTC081]
    lappend payload [list {S2KCP065} $S2KCP065]
    lappend payload [list {S2KCP066} $S2KCP066]
    lappend payload [list {S2KCP067} $S2KCP067]
    return $payload
}

proc TC_14_11 {} {
    # S2KTC082: Report Enabled Diagnostic Packets
    set payload [list S2KTC082]
    return $payload
}

proc TC_14_13 {S2KCP065 S2KCP066 S2KCP068} {
    # S2KTC083: Enable Forwarding Of Event Report Packets
    set payload [list S2KTC083]
    lappend payload [list {S2KCP065} $S2KCP065]
    lappend payload [list {S2KCP066} $S2KCP066]
    lappend payload [list {S2KCP068} $S2KCP068]
    return $payload
}

proc TC_14_14 {S2KCP065 S2KCP066 S2KCP068} {
    # S2KTC084: Disable Forwarding Of Event Report Packets
    set payload [list S2KTC084]
    lappend payload [list {S2KCP065} $S2KCP065]
    lappend payload [list {S2KCP066} $S2KCP066]
    lappend payload [list {S2KCP068} $S2KCP068]
    return $payload
}

proc TC_14_15 {} {
    # S2KTC085: Report Enabled Event Report Packets
    set payload [list S2KTC085]
    return $payload
}

proc TC_15_1 {S2KCP069} {
    # S2KTC086: Enable Storage In Packet Stores
    set payload [list S2KTC086]
    lappend payload [list {S2KCP069} $S2KCP069]
    return $payload
}

proc TC_15_2 {S2KCP069} {
    # S2KTC087: Disable Storage In Packet Stores
    set payload [list S2KTC087]
    lappend payload [list {S2KCP069} $S2KCP069]
    return $payload
}

proc TC_15_3 {S2KCP059 S2KCP060 S2KCP061 S2KCP062 S2KCP063 S2KCP064} {
    # S2KTC088: Add Packets To Storage Selection Definition
    set payload [list S2KTC088]
    lappend payload [list {S2KCP059} $S2KCP059]
    lappend payload [list {S2KCP060} $S2KCP060]
    lappend payload [list {S2KCP061} $S2KCP061]
    lappend payload [list {S2KCP062} $S2KCP062]
    lappend payload [list {S2KCP063} $S2KCP063]
    lappend payload [list {S2KCP064} $S2KCP064]
    return $payload
}

proc TC_15_4 {S2KCP059 S2KCP060 S2KCP061 S2KCP062 S2KCP063 S2KCP064} {
    # S2KTC089: Remove Packets From Storage Selection Definition
    set payload [list S2KTC089]
    lappend payload [list {S2KCP059} $S2KCP059]
    lappend payload [list {S2KCP060} $S2KCP060]
    lappend payload [list {S2KCP061} $S2KCP061]
    lappend payload [list {S2KCP062} $S2KCP062]
    lappend payload [list {S2KCP063} $S2KCP063]
    lappend payload [list {S2KCP064} $S2KCP064]
    return $payload
}

proc TC_15_5 {S2KCP069} {
    # S2KTC090: Report Storage Selection Definition
    set payload [list S2KTC090]
    lappend payload [list {S2KCP069} $S2KCP069]
    return $payload
}

proc TC_15_7 {S2KCP070 S2KCP071 S2KCP072 S2KCP073 S2KCP074} {
    # S2KTC091: Downlink Packet Store Contents For Packet Range
    set payload [list S2KTC091]
    lappend payload [list {S2KCP070} $S2KCP070]
    lappend payload [list {S2KCP071} $S2KCP071]
    lappend payload [list {S2KCP072} $S2KCP072]
    lappend payload [list {S2KCP073} $S2KCP073]
    lappend payload [list {S2KCP074} $S2KCP074]
    return $payload
}

proc TC_15_9 {S2KCP075 S2KCP076} {
    # S2KTC092: Downlink Packet Store Contents For Time Period
    set payload [list S2KTC092]
    lappend payload [list {S2KCP075} $S2KCP075]
    lappend payload [list {S2KCP076} $S2KCP076]
    return $payload
}

proc TC_15_10 {S2KCP077 S2KCP060 S2KCP078} {
    # S2KTC093: Delete Packet Stores Contents Up To Specified Packet
    set payload [list S2KTC093]
    lappend payload [list {S2KCP077} $S2KCP077]
    lappend payload [list {S2KCP060} $S2KCP060]
    lappend payload [list {S2KCP078} $S2KCP078]
    return $payload
}

proc TC_15_11 {S2KCP079} {
    # S2KTC094: Delete Packet Stores Contents Up To Specified Storage Time
    set payload [list S2KTC094]
    lappend payload [list {S2KCP079} $S2KCP079]
    return $payload
}

proc TC_15_12 {} {
    # S2KTC095: Report Catalogues For Selected Packet Stores
    set payload [list S2KTC095]
    return $payload
}

proc TC_17_1 {} {
    # S2KTC096: Perform Connection Test
    set payload [list S2KTC096]
    return $payload
}

proc TC_18_1 {S2KCP080 S2KCP081 args} {
    # S2KTC097: Load Procedure
    set payload [list S2KTC097]
    lappend payload [list {S2KCP080} $S2KCP080]
    lappend payload [list {S2KCP081} $S2KCP081]
    # Variable-length parameter(s): S2KCP082
    if {[llength $args] > 0} { lappend payload [list {S2KCP082} $args] }
    return $payload
}

proc TC_18_2 {S2KCP080} {
    # S2KTC098: Delete Procedure
    set payload [list S2KTC098]
    lappend payload [list {S2KCP080} $S2KCP080]
    return $payload
}

proc TC_18_3 {S2KCP080} {
    # S2KTC099: Start Procedure
    set payload [list S2KTC099]
    lappend payload [list {S2KCP080} $S2KCP080]
    return $payload
}

proc TC_18_4 {S2KCP080} {
    # S2KTC100: Stop Procedure
    set payload [list S2KTC100]
    lappend payload [list {S2KCP080} $S2KCP080]
    return $payload
}

proc TC_18_5 {S2KCP080} {
    # S2KTC101: Suspend Procedure
    set payload [list S2KTC101]
    lappend payload [list {S2KCP080} $S2KCP080]
    return $payload
}

proc TC_18_6 {S2KCP080} {
    # S2KTC102: Resume Procedure
    set payload [list S2KTC102]
    lappend payload [list {S2KCP080} $S2KCP080]
    return $payload
}

proc TC_18_7 {S2KCP080 S2KCP083 S2KCP084 S2KCP085} {
    # S2KTC103: Communicate Parameters To A Procedure
    set payload [list S2KTC103]
    lappend payload [list {S2KCP080} $S2KCP080]
    lappend payload [list {S2KCP083} $S2KCP083]
    lappend payload [list {S2KCP084} $S2KCP084]
    lappend payload [list {S2KCP085} $S2KCP085]
    return $payload
}

proc TC_18_8 {} {
    # S2KTC104: Report List Of On-board Operations Procedures
    set payload [list S2KTC104]
    return $payload
}

proc TC_18_10 {} {
    # S2KTC105: Report List Of Active On-board Operations Procedures
    set payload [list S2KTC105]
    return $payload
}

proc TC_18_12 {S2KCP080} {
    # S2KTC106: Abort Procedure
    set payload [list S2KTC106]
    lappend payload [list {S2KCP080} $S2KCP080]
    return $payload
}

proc TC_19_1 {S2KCP086 S2KCP087 args} {
    # S2KTC107: Add Events To The Detection List
    set payload [list S2KTC107]
    lappend payload [list {S2KCP086} $S2KCP086]
    lappend payload [list {S2KCP087} $S2KCP087]
    # Variable-length parameter(s): S2KCP088
    if {[llength $args] > 0} { lappend payload [list {S2KCP088} $args] }
    return $payload
}

proc TC_19_2 {S2KCP086 S2KCP087} {
    # S2KTC108: Delete Events From The Detection List
    set payload [list S2KTC108]
    lappend payload [list {S2KCP086} $S2KCP086]
    lappend payload [list {S2KCP087} $S2KCP087]
    return $payload
}

proc TC_19_3 {} {
    # S2KTC109: Clear The Event Detection List
    set payload [list S2KTC109]
    return $payload
}

proc TC_19_4 {S2KCP086 S2KCP087} {
    # S2KTC110: Enable Actions
    set payload [list S2KTC110]
    lappend payload [list {S2KCP086} $S2KCP086]
    lappend payload [list {S2KCP087} $S2KCP087]
    return $payload
}

proc TC_19_5 {S2KCP086 S2KCP087} {
    # S2KTC111: Disable Actions
    set payload [list S2KTC111]
    lappend payload [list {S2KCP086} $S2KCP086]
    lappend payload [list {S2KCP087} $S2KCP087]
    return $payload
}

proc TC_19_6 {} {
    # S2KTC112: Report The Event Detection List
    set payload [list S2KTC112]
    return $payload
}

proc TC_8_1_S2KTC113 {S2KCP034 S2KCP091 S2KCP092 S2KCP093} {
    # S2KTC113: Perform Function
    set payload [list S2KTC113]
    lappend payload [list {S2KCP034} $S2KCP034]
    lappend payload [list {S2KCP091} $S2KCP091]
    lappend payload [list {S2KCP092} $S2KCP092]
    lappend payload [list {S2KCP093} $S2KCP093]
    return $payload
}

proc TC_17_1_Header_3 {S2KCP107} {
    # S2KTC114: Perform connection test using Header type 3
    set payload [list S2KTC114]
    lappend payload [list {S2KCP107} $S2KCP107]
    return $payload
}

proc TC_17_1_Enum_param {S2KCP100 S2KCP101 S2KCP102 S2KCP103 S2KCP104 S2KCP105 S2KCP106} {
    # S2KTC115: Test command, using enumerated parameters
    set payload [list S2KTC115]
    lappend payload [list {S2KCP100} $S2KCP100]
    lappend payload [list {S2KCP101} $S2KCP101]
    lappend payload [list {S2KCP102} $S2KCP102]
    lappend payload [list {S2KCP103} $S2KCP103]
    lappend payload [list {S2KCP104} $S2KCP104]
    lappend payload [list {S2KCP105} $S2KCP105]
    lappend payload [list {S2KCP106} $S2KCP106]
    return $payload
}

proc TC_3_6_S2KTC116 {S2KCP013} {
    # S2KTC116: Set PUS ACK Flag=0
    set payload [list S2KTC116]
    lappend payload [list {S2KCP013} $S2KCP013]
    return $payload
}

proc TC_3_6_S2KTC117 {S2KCP013} {
    # S2KTC117: Test CVE_CHECK
    set payload [list S2KTC117]
    lappend payload [list {S2KCP013} $S2KCP013]
    return $payload
}

proc Test_I_L_for_SCC_only {S2KCP013} {
    # S2KTC118: 
    set payload [list S2KTC118]
    lappend payload [list {S2KCP013} $S2KCP013]
    return $payload
}

proc Dynamic_Defaults {S2KCP008 S2KCP009} {
    # S2KTC119: 
    set payload [list S2KTC119]
    lappend payload [list {S2KCP008} $S2KCP008]
    lappend payload [list {S2KCP009} $S2KCP009]
    return $payload
}

proc Editable_repeated_param {S2KCP059 S2KCP060} {
    # S2KTC120: 
    set payload [list S2KTC120]
    lappend payload [list {S2KCP059} $S2KCP059]
    lappend payload [list {S2KCP060} $S2KCP060]
    return $payload
}

proc Very_Large_TC {S2KCP059 S2KCP108} {
    # S2KTC121: 
    set payload [list S2KTC121]
    lappend payload [list {S2KCP059} $S2KCP059]
    lappend payload [list {S2KCP108} $S2KCP108]
    return $payload
}

proc TC_7_16_Gaps {S2KCP001 S2KCP002 S2KCP003} {
    # S2KTC122: 
    set payload [list S2KTC122]
    lappend payload [list {S2KCP001} $S2KCP001]
    lappend payload [list {S2KCP002} $S2KCP002]
    lappend payload [list {S2KCP003} $S2KCP003]
    return $payload
}

proc Multiple_Echo_Verif {S2KCP001 S2KCP002 S2KCP003} {
    # S2KTC123: 
    set payload [list S2KTC123]
    lappend payload [list {S2KCP001} $S2KCP001]
    lappend payload [list {S2KCP002} $S2KCP002]
    lappend payload [list {S2KCP003} $S2KCP003]
    return $payload
}

proc TC_11_1_Rosetta {S2KCP301 S2KCP302 {PAD_8 {}} {PAD_5 {}}} {
    # S2KTC301: Enable Release Of Telecommands (Rosetta compatibility)
    set payload [list S2KTC301]
    lappend payload [list {S2KCP301} $S2KCP301]
    lappend payload [list {S2KCP302} $S2KCP302]
    if {$PAD_8 ne ""} { lappend payload [list {PAD_8} $PAD_8] }
    if {$PAD_5 ne ""} { lappend payload [list {PAD_5} $PAD_5] }
    return $payload
}

proc TC_11_2_Rosetta {S2KCP301 S2KCP302 {PAD_8 {}} {PAD_5 {}}} {
    # S2KTC302: Disable Release Of Selected TCs (Rosetta compatibility)
    set payload [list S2KTC302]
    lappend payload [list {S2KCP301} $S2KCP301]
    lappend payload [list {S2KCP302} $S2KCP302]
    if {$PAD_8 ne ""} { lappend payload [list {PAD_8} $PAD_8] }
    if {$PAD_5 ne ""} { lappend payload [list {PAD_5} $PAD_5] }
    return $payload
}

proc TC_11_3_Rosetta {} {
    # S2KTC303: Reset Command Schedule (Rosetta compatibility)
    set payload [list S2KTC303]
    return $payload
}

proc TC_11_4_Rosetta {S2KCP303 S2KCP301 {PAD_8 {}} args} {
    # S2KTC304: Insert TCs In Command Schedule (Rosetta compatibility)
    set payload [list S2KTC304]
    lappend payload [list {S2KCP303} $S2KCP303]
    lappend payload [list {S2KCP301} $S2KCP301]
    if {$PAD_8 ne ""} { lappend payload [list {PAD_8} $PAD_8] }
    # Variable-length parameter(s): S2KCP304
    if {[llength $args] > 0} { lappend payload [list {S2KCP304} $args] }
    return $payload
}

proc TC_11_5_Rosetta {S2KCP302 S2KCP305 S2KCP306 {PAD_5 {}} {PAD_2 {}} {PAD_8 {}}} {
    # S2KTC305: Delete TCs by APID and Sequence Counter  (Rosetta compatibility)
    set payload [list S2KTC305]
    lappend payload [list {S2KCP302} $S2KCP302]
    lappend payload [list {S2KCP305} $S2KCP305]
    lappend payload [list {S2KCP306} $S2KCP306]
    if {$PAD_5 ne ""} { lappend payload [list {PAD_5} $PAD_5] }
    if {$PAD_2 ne ""} { lappend payload [list {PAD_2} $PAD_2] }
    if {$PAD_8 ne ""} { lappend payload [list {PAD_8} $PAD_8] }
    return $payload
}

proc TC_11_6_Rosetta {S2KCP307 S2KCP308 S2KCP309 S2KCP301 S2KCP302 {PAD_14 {}} {PAD_8 {}} {PAD_5 {}}} {
    # S2KTC306: Delete TCs over Time Period (Rosetta compatibility)
    set payload [list S2KTC306]
    lappend payload [list {S2KCP307} $S2KCP307]
    lappend payload [list {S2KCP308} $S2KCP308]
    lappend payload [list {S2KCP309} $S2KCP309]
    lappend payload [list {S2KCP301} $S2KCP301]
    lappend payload [list {S2KCP302} $S2KCP302]
    if {$PAD_14 ne ""} { lappend payload [list {PAD_14} $PAD_14] }
    if {$PAD_8 ne ""} { lappend payload [list {PAD_8} $PAD_8] }
    if {$PAD_5 ne ""} { lappend payload [list {PAD_5} $PAD_5] }
    return $payload
}

proc TC_11_8_Rosetta {S2KCP307 S2KCP308 S2KCP309 S2KCP310 S2KCP301 S2KCP302 {PAD_14 {}} {PAD_8 {}} {PAD_5 {}}} {
    # S2KTC308: Time-Shift TCs over Time Period (Rosetta compatibility)
    set payload [list S2KTC308]
    lappend payload [list {S2KCP307} $S2KCP307]
    lappend payload [list {S2KCP308} $S2KCP308]
    lappend payload [list {S2KCP309} $S2KCP309]
    lappend payload [list {S2KCP310} $S2KCP310]
    lappend payload [list {S2KCP301} $S2KCP301]
    lappend payload [list {S2KCP302} $S2KCP302]
    if {$PAD_14 ne ""} { lappend payload [list {PAD_14} $PAD_14] }
    if {$PAD_8 ne ""} { lappend payload [list {PAD_8} $PAD_8] }
    if {$PAD_5 ne ""} { lappend payload [list {PAD_5} $PAD_5] }
    return $payload
}

proc Unlock_Control_Command {{Unlock_Octet {}}} {
    # S2KTC501: FARM Directives: Unlock Control Command
    set payload [list S2KTC501]
    if {$Unlock_Octet ne ""} { lappend payload [list {Unlock Octet} $Unlock_Octet] }
    return $payload
}

proc SetV_R_Control_Command {S2KCP501 {SetV_R_Octet_1 {}} {SetV_R_Octet_2 {}}} {
    # S2KTC502: FARM directive: Set V(R) Control Command
    set payload [list S2KTC502]
    lappend payload [list {S2KCP501} $S2KCP501]
    if {$SetV_R_Octet_1 ne ""} { lappend payload [list {SetV(R) Octet 1} $SetV_R_Octet_1] }
    if {$SetV_R_Octet_2 ne ""} { lappend payload [list {SetV(R) Octet 2} $SetV_R_Octet_2] }
    return $payload
}

proc Reset_MAP {S2KCP502 {Reset_MAP_FIXED_AREA {}}} {
    # S2KTC503: Reset MAP command
    set payload [list S2KTC503]
    lappend payload [list {S2KCP502} $S2KCP502]
    if {$Reset_MAP_FIXED_AREA ne ""} { lappend payload [list {Reset MAP FIXED AREA} $Reset_MAP_FIXED_AREA] }
    return $payload
}

proc TC_8_1_signed_pars {S2KCP400 S2KCP401 S2KCP402 S2KCP403 S2KCP405 S2KCP406 S2KCP407 S2KCP408 S2KCP409 S2KCP410 S2KCP411 S2KCP413 S2KCP414} {
    # S2KTC601: Perform function command containing signed params
    set payload [list S2KTC601]
    lappend payload [list {S2KCP400} $S2KCP400]
    lappend payload [list {S2KCP401} $S2KCP401]
    lappend payload [list {S2KCP402} $S2KCP402]
    lappend payload [list {S2KCP403} $S2KCP403]
    lappend payload [list {S2KCP405} $S2KCP405]
    lappend payload [list {S2KCP406} $S2KCP406]
    lappend payload [list {S2KCP407} $S2KCP407]
    lappend payload [list {S2KCP408} $S2KCP408]
    lappend payload [list {S2KCP409} $S2KCP409]
    lappend payload [list {S2KCP410} $S2KCP410]
    lappend payload [list {S2KCP411} $S2KCP411]
    lappend payload [list {S2KCP413} $S2KCP413]
    lappend payload [list {S2KCP414} $S2KCP414]
    return $payload
}

proc TC_18_1_time_params {S2KCP902 S2KCP903 S2KCP904 S2KCP905 S2KCP906 S2KCP907 S2KCP908 S2KCP910 S2KCP911 S2KCP912 S2KCP913 S2KCP915 S2KCP916 S2KCP917 S2KCP918} {
    # S2KTC602: Perform function, time parameters
    set payload [list S2KTC602]
    lappend payload [list {S2KCP902} $S2KCP902]
    lappend payload [list {S2KCP903} $S2KCP903]
    lappend payload [list {S2KCP904} $S2KCP904]
    lappend payload [list {S2KCP905} $S2KCP905]
    lappend payload [list {S2KCP906} $S2KCP906]
    lappend payload [list {S2KCP907} $S2KCP907]
    lappend payload [list {S2KCP908} $S2KCP908]
    lappend payload [list {S2KCP910} $S2KCP910]
    lappend payload [list {S2KCP911} $S2KCP911]
    lappend payload [list {S2KCP912} $S2KCP912]
    lappend payload [list {S2KCP913} $S2KCP913]
    lappend payload [list {S2KCP915} $S2KCP915]
    lappend payload [list {S2KCP916} $S2KCP916]
    lappend payload [list {S2KCP917} $S2KCP917]
    lappend payload [list {S2KCP918} $S2KCP918]
    return $payload
}

proc TC_255_255 {S2KCP320 S2KCP330 S2KCP350 S2KCP360 S2KCP370 S2KCP380 S2KCP390 S2KCP311 S2KCP313 S2KCP503 S2KCP504 S2KCP200 S2KCP701 S2KCP300} {
    # S2KTC603: A command reaching the range limits (out of PUS services)
    set payload [list S2KTC603]
    lappend payload [list {S2KCP320} $S2KCP320]
    lappend payload [list {S2KCP330} $S2KCP330]
    lappend payload [list {S2KCP350} $S2KCP350]
    lappend payload [list {S2KCP360} $S2KCP360]
    lappend payload [list {S2KCP370} $S2KCP370]
    lappend payload [list {S2KCP380} $S2KCP380]
    lappend payload [list {S2KCP390} $S2KCP390]
    lappend payload [list {S2KCP311} $S2KCP311]
    lappend payload [list {S2KCP313} $S2KCP313]
    lappend payload [list {S2KCP503} $S2KCP503]
    lappend payload [list {S2KCP504} $S2KCP504]
    lappend payload [list {S2KCP200} $S2KCP200]
    lappend payload [list {S2KCP701} $S2KCP701]
    lappend payload [list {S2KCP300} $S2KCP300]
    return $payload
}

proc TC_255_64 {S2KCP209 S2KCP210 S2KCP212 S2KCP213 S2KCP214 S2KCP215 S2KCP217 S2KCP218 S2KCP219 S2KCP220 S2KCP221 S2KCP222 S2KCP223 S2KCP224 S2KCP225 S2KCP226 S2KCP227 S2KCP228 S2KCP229 S2KCP230 S2KCP231 args} {
    # S2KTC604: Large list of unsigned params. Out of PUS services
    set payload [list S2KTC604]
    lappend payload [list {S2KCP209} $S2KCP209]
    lappend payload [list {S2KCP210} $S2KCP210]
    lappend payload [list {S2KCP212} $S2KCP212]
    lappend payload [list {S2KCP213} $S2KCP213]
    lappend payload [list {S2KCP214} $S2KCP214]
    lappend payload [list {S2KCP215} $S2KCP215]
    lappend payload [list {S2KCP217} $S2KCP217]
    lappend payload [list {S2KCP218} $S2KCP218]
    lappend payload [list {S2KCP219} $S2KCP219]
    lappend payload [list {S2KCP220} $S2KCP220]
    lappend payload [list {S2KCP221} $S2KCP221]
    lappend payload [list {S2KCP222} $S2KCP222]
    lappend payload [list {S2KCP223} $S2KCP223]
    lappend payload [list {S2KCP224} $S2KCP224]
    lappend payload [list {S2KCP225} $S2KCP225]
    lappend payload [list {S2KCP226} $S2KCP226]
    lappend payload [list {S2KCP227} $S2KCP227]
    lappend payload [list {S2KCP228} $S2KCP228]
    lappend payload [list {S2KCP229} $S2KCP229]
    lappend payload [list {S2KCP230} $S2KCP230]
    lappend payload [list {S2KCP231} $S2KCP231]
    # Variable-length parameter(s): S2KCP800
    if {[llength $args] > 0} { lappend payload [list {S2KCP800} $args] }
    return $payload
}

proc Command_ID {args} {
    # S2KTC700: 
    set payload [list S2KTC700]
    # Variable-length parameter(s): S2KCP900
    if {[llength $args] > 0} { lappend payload [list {S2KCP900} $args] }
    return $payload
}

proc Command_ID_default {args} {
    # S2KTC701: 
    set payload [list S2KTC701]
    # Variable-length parameter(s): S2KCP900
    if {[llength $args] > 0} { lappend payload [list {S2KCP900} $args] }
    return $payload
}

proc Parameter_ID {S2KCP901} {
    # S2KTC702: 
    set payload [list S2KTC702]
    lappend payload [list {S2KCP901} $S2KCP901]
    return $payload
}

proc Parameter_ID_default {S2KCP901} {
    # S2KTC703: 
    set payload [list S2KTC703]
    lappend payload [list {S2KCP901} $S2KCP901]
    return $payload
}

proc Cmd_ID_Param_ID {S2KCP901 args} {
    # S2KTC704: Invalid default values
    set payload [list S2KTC704]
    lappend payload [list {S2KCP901} $S2KCP901]
    # Variable-length parameter(s): S2KCP900
    if {[llength $args] > 0} { lappend payload [list {S2KCP900} $args] }
    return $payload
}

proc ThrowEvent_Test1 {{Event_Identifier {}} args} {
    # S2KTCTE1: 
    set payload [list S2KTCTE1]
    if {$Event_Identifier ne ""} { lappend payload [list {Event Identifier} $Event_Identifier] }
    # Variable-length parameter(s): S2KCPTHE
    if {[llength $args] > 0} { lappend payload [list {S2KCPTHE} $args] }
    return $payload
}

proc ThrowEvent_Test2 {S2KCPEVI args} {
    # S2KTCTE2: 
    set payload [list S2KTCTE2]
    lappend payload [list {S2KCPEVI} $S2KCPEVI]
    # Variable-length parameter(s): S2KCPSTR
    if {[llength $args] > 0} { lappend payload [list {S2KCPSTR} $args] }
    return $payload
}

